steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project-e86cb23b-a4f9-410f-b18/omnicanal-financiero:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project-e86cb23b-a4f9-410f-b18/omnicanal-financiero:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'omnicanal-app', '--image', 'gcr.io/project-e86cb23b-a4f9-410f-b18/omnicanal-financiero:latest', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
